services:
    BaptisteDulac\PushNotificationBundle\Sender\AndroidSender:
        arguments:
            - '%baptiste_dulac_push_notification.android.api_key%'
            - '%baptiste_dulac_push_notification.android.timeout%'