services:
    BaptisteDulac\PushNotificationBundle\Sender\IOSSender:
        arguments:
            - '%baptiste_dulac_push_notification.ios.pem%'
            - '%baptiste_dulac_push_notification.ios.passphrase%'
            - '%baptiste_dulac_push_notification.ios.sandbox%'
            - '%baptiste_dulac_push_notification.ios.timeout%'